<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 text-center">
            <h2 class="section-title">Veja as útimas vagas adicionadas</h2>
        </div>

        <?php
        foreach ($this->view->dados as $indice => $emprego) { ?>


            <div class="col-xl-12 col-md-12 mb-4">
                <div class="card">
                    <div class="two">
                        <div class="d-flex justify-content-end px-3 pt-2"><i class="bi bi-star"></i></i><i class="mdi mdi-dots-horizontal dot"></i></div>
                        <div class="px-3">
                            <div class="round"><img src="https://img.icons8.com/bubbles/100/000000/girl-with-glasses-art-palette.png" width="50" /></div>
                        </div>
                        <div class="px-3 pt-3">
                            <h3 class="name"><?= $emprego['titulo']; ?></h3> 
                            <p class="quote2"><?= $emprego['descricao']; ?></p>
                        </div>
                        <div class="d-flex justify-content-start px-3 align-items-center">
                            <i class="bi bi-list-task"></i>
                            <span class="quote2 pl-2">Tarefa: <?= $emprego['modalidade']; ?></span>
                        </div>
                        <div class="d-flex justify-content-between  px-3 align-items-center pb-3">
                            <div class="d-flex justify-content-start align-items-center">
                                <i class="bi bi-calendar3"></i>
                                <span class="quote2 pl-2">Data: <?= date('d/m/Y', strtotime($emprego['created_at']))  ?></span>
                            </div>
                            <div class="d-flex justify-content-end">
                                <button type="button" class="btn btn-primary">Ver Vaga</button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>


        <?php } ?>






    </div>
</div>