<div class="container">
    <div class="row ">
        <h2 class="section-title text-primary text-center mb-5">Informações da vaga</h2>
        <div class="d-flex flex-column">
            <img src="assets/uploads/usuario/<?= $this->view->dados['imagem'] ?>" class="img-fluid rounded-start m-auto"
                width="64">

            <h2 class="section-title text-primary mb-2 mt-2 fs-4 text-center">
                <?= $this->view->dados['titulo'] ?>
            </h2>
            <p class="fw-bold fs-5 mb-0 text-center">
                <?= $this->view->dados['nome'] . ' ' . $this->view->dados['sobrenome'] ?>
            </p>
        </div>

        <div class="col-md-6">

            <p class="fw-bold mb-0 text-center mt-3">
                <?= "Local de Trabalho:" ?>
            </p>
            <p class="text-center">
                <?= $this->view->dados['local_trabalho']; ?>
            </p>
            <p class="fw-bold mb-0 text-center">
                <?= "Descrição:" ?>
            </p>
            <p class="text-center">
                <?= $this->view->dados['descricao']; ?>
            </p>
            <p class="fw-bold mb-0 text-center">

                <?= "Habilidades:" ?>
            </p>
            <p class="text-center ">
                <?php
                $skills = explode(";", $this->view->dados['habilidade']);
                foreach ($skills as $key => $valor) {
                    ?>
                    <span class="badge bg-primary ">
                        <?= $valor ?>
                    </span>
                    <?php
                }
                ?>
            </p>

        </div>
        <div class="col-md-6">
            <p class="fw-bold fs-6 mt-3 mb-1 text-center">
                <?= "Interessados entrar em contato por:" ?>
            </p>
            <p class="mb-0 text-center">Telefone:
                <?= $this->view->dados['telefone']; ?>
            </p>
            <p class="text-center">E-mail:
                <?= $this->view->dados['email']; ?>
            </p>
            <?php
            $dias = diasDatas(date('Y-m-d', strtotime($this->view->dados['created_at'])), null);
            $data = date('d/m/Y', strtotime($this->view->dados['created_at'])) . ' - ' . $dias;
            $data .= $dias > 1 ? " dias atrás" : " dia atrás";
            ?>
            <p class="text-center">
                <?= $data; ?>
            </p>
            <!-- <span><img src="assets/img/novo2.svg" width="32"></span> -->
            <p class="text-center">
                <?php $qtde_vaga = $this->view->dados['qtde_vaga'] > 1 ? " vagas" : " vaga" ?>
                <?= $this->view->dados['modalidade'] . ' - ' . $this->view->dados['qtde_vaga'] . $qtde_vaga ?>
            </p>
            <p class="fs-3 text-center"><span class="badge bg-success">
                    <?= formatarMoeda($this->view->dados['salario'], "R$", 2) ?>
                </span></p>

        </div>

    </div>
    <hr>
    <a class="d-block text-center" href="/"><button type="button" class="btn btn-primary btn-sm ">Voltar</button></a>
</div>